### ISSUE TITLE
envoy基礎教程代礎因版本問題運行報錯

### ISSUE THREAD

**Issue by reply2future** [rootsongjc/docs#9]
## 問題
配署如下：
https://github.com/rootsongjc/docs/blob/8d5220a1d3d478cf421e96a1cb6cf594fffae85b/content/envoy-handbook/intro/envoy-building-blocks.md?plain=1#L94-L120

運行
https://github.com/rootsongjc/docs/blob/8d5220a1d3d478cf421e96a1cb6cf594fffae85b/content/envoy-handbook/intro/envoy-building-blocks.md?plain=1#L151

報錯
`Didn't find a registered implementation for 'envoy.filters.http.router' with type URL: ''`
使用envoy版本: 1.22

查看[官方例子](https://www.envoyproxy.io/docs/envoy/latest/configuration/overview/examples)，發現是1.22新增的屬性
![image](https://user-images.githubusercontent.com/6359152/169738396-c555e7df-65a1-4f09-b307-1a76c12a0a61.png)
參照修改之後成功運行

是否應該在書中指明envoy的版本會比較好，然後使用`func-e`指定全局版本，比如: `func-e use 1.20`

BTW，其他雲原生書籍也有同樣因沒有注明版本問題

**Comment by rootsongjc** [comment]
@reply2future 感谢你的提醒，我在你说的这个命令前增加了提示信息，见：https://jimmysong.io/docs/envoy-handbook/intro/envoy-building-blocks/

**Comment by rootsongjc** [comment]
@reply2future 感谢你的提醒，我在你说的这个命令前增加了提示信息，见：https://jimmysong.io/docs/envoy-handbook/intro/envoy-building-blocks/
